apiVersion: 1

contactPoints:
  - orgId: 1
    name: incident-responder
    receivers:
      - uid: responder-webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://host.docker.internal:8001/alerts
          httpMethod: POST

policies:
  - orgId: 1
    receiver: incident-responder
    group_by:
      - grafana_folder
      - alertname
    group_wait: 5s
    group_interval: 10s
    repeat_interval: 2m
    routes:
      - receiver: incident-responder
        object_matchers:
          - ["service", "=", "order-tracker"]
        continue: false